name: nixy_markdown
version: 0.1.4
homepage: https://github.com/MuhammedKpln/nixi-markdown
description: Markdown for nixi package.
environment: 
  sdk: '>=3.0.1 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  nixy_markdown_controller: ^0.1.3
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter: null
